/*
 *  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
 *
 *  Licensed under the Apache License 2.0 (the "License"). You may not use
 *  this file except in compliance with the License.  You can obtain a copy
 *  in the file LICENSE in the source distribution or at
 *  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE
 *
 */

package org.openssl.jostle.test.dsa;

import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openssl.jostle.jcajce.provider.JostleProvider;
import org.openssl.jostle.test.util.CipherFamilies;
import org.openssl.jostle.test.util.ProviderSurfaceGuard;
import org.openssl.jostle.util.Arrays;

import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.PrivateKey;
import java.security.Provider;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Security;
import java.security.Signature;
import java.security.spec.DSAParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.ArrayList;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Cross-provider agreement for the WHOLE base-provider ({@code JSL}) DSA
 * surface, against BouncyCastle.
 * <p>
 * Non-FIPS counterpart of {@link
 * org.openssl.jostle.test.fips.FIPSDSAAgreementTest}. That one cannot cover
 * this: it reads JSLFIPS's registered set, and a 3.5.x module configured with
 * {@code dsa-sign-disabled} refuses generation and signing outright, so the
 * base provider is the only place the whole surface can be driven.
 * <p>
 * <b>What "agrees" means differs by type, because byte-equality is only
 * available for one of them.</b>
 * <ol>
 * <li><b>Signature</b> — DSA picks a random per-signature nonce, so two
 * signatures of one message differ. Agreement is CROSS-VERIFICATION, run in
 * both directions for every registered name: JSL signs and BC verifies, then
 * BC signs and JSL verifies. One direction alone can pass with a verifier that
 * ignores the digest, so both are required.</li>
 * <li><b>KeyFactory</b> — byte-equality of the re-encoded key, both halves and
 * both directions.</li>
 * <li><b>AlgorithmParameters</b> — byte-equality of the Dss-Parms encoding, and
 * of {@code p}, {@code q}, {@code g} read back through the peer.</li>
 * <li><b>AlgorithmParameterGenerator</b> — generation is randomised, so
 * agreement is CROSS-ACCEPTANCE: parameters one provider generates must be
 * accepted by the other and yield a keypair that signs and verifies across the
 * boundary. Do not go looking for byte-equality here.</li>
 * </ol>
 * <b>Breadth, not depth.</b> {@link DSATest}, {@link DSASignatureTest} and
 * {@link DSANoneWithDSASignatureTest} keep the chunking, state-machine,
 * boundary and encoding coverage.
 * <p>
 * Key material crosses providers as encodings decoded through each provider's
 * own KeyFactory — the only sanctioned crossing, and what a real peer does.
 * <p>
 * Inputs come from a per-test SHA1PRNG whose seed is logged.
 */
public class DSAAgreementTest
{
    private static final String JSL = JostleProvider.PROVIDER_NAME;
    private static final String BC = BouncyCastleProvider.PROVIDER_NAME;

    /** The five JCA types {@code ProvDSA} registers under. */
    private static final String[] GUARDED_TYPES = {
            "AlgorithmParameterGenerator", "AlgorithmParameters",
            "KeyFactory", "KeyPairGenerator", "Signature"
    };

    /** FIPS 186-4 (L, N) = (2048, 256). Large enough to be legitimate, small enough to be quick. */
    private static final int KEY_BITS = 2048;

    /** Trials per registered name — one random message probes one point only. */
    private static final int TRIALS = 3;

    private static final SecureRandom RANDOM = new SecureRandom();

    /**
     * One keypair per JVM, generated by JSL and crossed to BC as encodings.
     * Generation is the expensive step and the keys are not what varies
     * between trials, so it is hoisted; messages stay random per trial.
     */
    private static KeyPair jslPair;
    private static PublicKey bcPub;
    private static PrivateKey bcPriv;

    @BeforeAll
    static void before() throws Exception
    {
        if (Security.getProvider(JSL) == null)
        {
            Security.addProvider(new JostleProvider());
        }
        if (Security.getProvider(BC) == null)
        {
            Security.addProvider(new BouncyCastleProvider());
        }

        KeyPairGenerator kpg = KeyPairGenerator.getInstance("DSA", JSL);
        kpg.initialize(KEY_BITS);
        jslPair = kpg.generateKeyPair();

        KeyFactory bcKf = KeyFactory.getInstance("DSA", BC);
        bcPub = bcKf.generatePublic(new X509EncodedKeySpec(jslPair.getPublic().getEncoded()));
        bcPriv = bcKf.generatePrivate(new PKCS8EncodedKeySpec(jslPair.getPrivate().getEncoded()));
    }

    private static SecureRandom seededRandom(String testName) throws Exception
    {
        long seed = RANDOM.nextLong();
        System.out.println(testName + " seed=" + seed);
        SecureRandom sr = SecureRandom.getInstance("SHA1PRNG");
        sr.setSeed(seed);
        return sr;
    }

    /** Every Signature primary {@code ProvDSA} registers, sorted. */
    private static List<String> registeredSignatures()
    {
        Provider provider = Security.getProvider(JSL);
        Assertions.assertNotNull(provider, "JSL provider is not registered");

        List<String> names = new ArrayList<String>();
        for (Provider.Service s : provider.getServices())
        {
            String cn = s.getClassName();
            if ("Signature".equals(s.getType()) && cn != null && cn.startsWith(CipherFamilies.DSA_PREFIX))
            {
                names.add(s.getAlgorithm());
            }
        }
        Assertions.assertFalse(names.isEmpty(), "JSL registered no DSA Signature services");
        java.util.Collections.sort(names);
        return names;
    }

    /**
     * {@code NoneWithDSA} is handed an already-computed digest rather than a
     * message. SHA-256 matches the 256-bit q of the test keypair, so the whole
     * digest is used rather than silently truncated.
     */
    private static boolean isPreHashed(String alg)
    {
        return "NONEWITHDSA".equalsIgnoreCase(alg);
    }

    private static byte[] signedBytes(String alg, byte[] message) throws Exception
    {
        if (isPreHashed(alg))
        {
            return MessageDigest.getInstance("SHA-256").digest(message);
        }
        return message;
    }

    private static byte[] sign(String alg, String provider, PrivateKey key, byte[] message) throws Exception
    {
        Signature s = Signature.getInstance(alg, provider);
        s.initSign(key);
        s.update(signedBytes(alg, message));
        return s.sign();
    }

    private static boolean verify(String alg, String provider, PublicKey key, byte[] message, byte[] sig)
            throws Exception
    {
        Signature v = Signature.getInstance(alg, provider);
        v.initVerify(key);
        v.update(signedBytes(alg, message));
        return v.verify(sig);
    }

    // -----------------------------------------------------------------
    // Completeness guard
    // -----------------------------------------------------------------

    /**
     * Every DSA service JSL registers is DRIVEN, discovered from the provider
     * by SPI class-name prefix rather than listed — so a registration added
     * later fails until someone teaches this an operation. Aliases are
     * included, which is what makes the OID spellings covered.
     * <p>
     * No covered list, for the reason {@code ProviderSurfaceGuard} documents:
     * a list drifts, and deriving one from the provider compares the provider
     * against itself. The removal direction is a per-TYPE floor below rather
     * than a per-name list — a family dropped wholesale fails here, and a
     * single name dropped is the golden snapshot's job.
     */
    @Test
    public void everyRegisteredDsaServiceIsDriven() throws Exception
    {
        final SecureRandom sr = seededRandom("everyRegisteredDsaServiceIsDriven");

        ProviderSurfaceGuard.assertEveryServiceDriven(Security.getProvider(JSL),
                CipherFamilies.DSA_PREFIX, "DSA (JSL)", GUARDED_TYPES,
                new ProviderSurfaceGuard.ServiceDriver()
                {
                    public void drive(String type, String alg) throws Exception
                    {
                        if ("Signature".equals(type))
                        {
                            byte[] msg = new byte[32];
                            sr.nextBytes(msg);
                            byte[] sig = sign(alg, JSL, jslPair.getPrivate(), msg);
                            Assertions.assertTrue(verify(alg, JSL, jslPair.getPublic(), msg, sig),
                                    alg + ": did not verify its own signature");
                        }
                        else if ("KeyFactory".equals(type))
                        {
                            PublicKey pub = KeyFactory.getInstance(alg, JSL)
                                    .generatePublic(new X509EncodedKeySpec(jslPair.getPublic().getEncoded()));
                            Assertions.assertTrue(
                                    Arrays.areEqual(jslPair.getPublic().getEncoded(), pub.getEncoded()), alg);
                        }
                        else if ("KeyPairGenerator".equals(type))
                        {
                            KeyPairGenerator kpg = KeyPairGenerator.getInstance(alg, JSL);
                            kpg.initialize(KEY_BITS);
                            KeyPair kp = kpg.generateKeyPair();
                            byte[] msg = new byte[32];
                            sr.nextBytes(msg);
                            byte[] sig = sign("SHA256withDSA", JSL, kp.getPrivate(), msg);
                            Assertions.assertTrue(
                                    verify("SHA256withDSA", JSL, kp.getPublic(), msg, sig),
                                    alg + ": generated a keypair that cannot sign");
                        }
                        else if ("AlgorithmParameters".equals(type))
                        {
                            AlgorithmParameters ap = AlgorithmParameters.getInstance(alg, JSL);
                            ap.init(domainOf(jslPair));
                            Assertions.assertNotNull(ap.getEncoded(), alg);
                        }
                        else if ("AlgorithmParameterGenerator".equals(type))
                        {
                            AlgorithmParameterGenerator apg =
                                    AlgorithmParameterGenerator.getInstance(alg, JSL);
                            apg.init(KEY_BITS);
                            DSAParameterSpec spec = apg.generateParameters()
                                    .getParameterSpec(DSAParameterSpec.class);
                            Assertions.assertEquals(KEY_BITS, spec.getP().bitLength(),
                                    alg + ": generated p of the wrong size");
                        }
                        else
                        {
                            throw new IllegalStateException("no drive defined for " + type + "." + alg
                                    + " — teach this driver rather than letting it go unexercised");
                        }
                    }
                });
    }

    /**
     * The removal direction, at type granularity: each of the five JCA types
     * {@code ProvDSA} registers under must still be present. A per-name list
     * would drift; this catches a family dropped wholesale, which is the shape
     * a refactor actually produces.
     */
    @Test
    public void everyGuardedTypeIsStillRegistered()
    {
        SortedSet<String> surface = ProviderSurfaceGuard.registeredSurface(
                Security.getProvider(JSL), CipherFamilies.DSA_PREFIX, GUARDED_TYPES);

        SortedSet<String> missing = new TreeSet<String>();
        for (String type : GUARDED_TYPES)
        {
            boolean found = false;
            for (String entry : surface)
            {
                if (entry.startsWith(type + "."))
                {
                    found = true;
                    break;
                }
            }
            if (!found)
            {
                missing.add(type);
            }
        }
        Assertions.assertTrue(missing.isEmpty(),
                "JSL no longer registers any DSA service of these types: " + missing);
    }

    // -----------------------------------------------------------------
    // Signature — cross-verification, both directions
    // -----------------------------------------------------------------

    /**
     * For every registered DSA Signature name: JSL signs and BC verifies, and
     * BC signs and JSL verifies. Both directions, because a verifier that
     * ignored the digest entirely would pass either one alone.
     * <p>
     * Differentiator per trial: a one-byte change to the message must fail
     * verification on the peer, so a verifier returning a constant {@code true}
     * cannot pass.
     */
    @Test
    public void everyRegisteredSignatureCrossVerifiesWithBouncyCastle() throws Exception
    {
        SecureRandom sr = seededRandom("everyRegisteredSignatureCrossVerifiesWithBouncyCastle");

        for (String alg : registeredSignatures())
        {
            for (int t = 0; t < TRIALS; t++)
            {
                byte[] message = new byte[1 + sr.nextInt(2048)];
                sr.nextBytes(message);

                byte[] jslSig = sign(alg, JSL, jslPair.getPrivate(), message);
                Assertions.assertTrue(verify(alg, BC, bcPub, message, jslSig),
                        alg + ": BC rejected a JSL signature");

                byte[] bcSig = sign(alg, BC, bcPriv, message);
                Assertions.assertTrue(verify(alg, JSL, jslPair.getPublic(), message, bcSig),
                        alg + ": JSL rejected a BC signature");

                byte[] tampered = message.clone();
                tampered[sr.nextInt(tampered.length)] ^= (byte) (1 + sr.nextInt(255));
                Assertions.assertFalse(verify(alg, BC, bcPub, tampered, jslSig),
                        alg + ": BC accepted a JSL signature over a tampered message");
                Assertions.assertFalse(verify(alg, JSL, jslPair.getPublic(), tampered, bcSig),
                        alg + ": JSL accepted a BC signature over a tampered message");
            }
        }
    }

    // -----------------------------------------------------------------
    // KeyFactory — byte-equality of re-encoded keys, both directions
    // -----------------------------------------------------------------

    /**
     * A keypair generated by either provider must re-encode identically
     * through the other, on both halves — so a wrong OID or a mis-encoded
     * Dss-Parms in the AlgorithmIdentifier is caught rather than tolerated.
     */
    @Test
    public void keysRoundTripThroughBothKeyFactories() throws Exception
    {
        SecureRandom sr = seededRandom("keysRoundTripThroughBothKeyFactories");

        KeyFactory jslKf = KeyFactory.getInstance("DSA", JSL);
        KeyFactory bcKf = KeyFactory.getInstance("DSA", BC);

        // JSL-generated, re-encoded by BC.
        Assertions.assertTrue(Arrays.areEqual(jslPair.getPublic().getEncoded(),
                        bcKf.generatePublic(new X509EncodedKeySpec(
                                jslPair.getPublic().getEncoded())).getEncoded()),
                "BC re-encoded a JSL public key differently");
        Assertions.assertTrue(Arrays.areEqual(jslPair.getPrivate().getEncoded(),
                        bcKf.generatePrivate(new PKCS8EncodedKeySpec(
                                jslPair.getPrivate().getEncoded())).getEncoded()),
                "BC re-encoded a JSL private key differently");

        // BC-generated, re-encoded by JSL.
        KeyPairGenerator bcKpg = KeyPairGenerator.getInstance("DSA", BC);
        bcKpg.initialize(KEY_BITS);
        KeyPair bcPair = bcKpg.generateKeyPair();

        PublicKey viaJslPub = jslKf.generatePublic(
                new X509EncodedKeySpec(bcPair.getPublic().getEncoded()));
        PrivateKey viaJslPriv = jslKf.generatePrivate(
                new PKCS8EncodedKeySpec(bcPair.getPrivate().getEncoded()));
        Assertions.assertTrue(Arrays.areEqual(bcPair.getPublic().getEncoded(), viaJslPub.getEncoded()),
                "JSL re-encoded a BC public key differently");
        Assertions.assertTrue(Arrays.areEqual(bcPair.getPrivate().getEncoded(), viaJslPriv.getEncoded()),
                "JSL re-encoded a BC private key differently");

        // And the round-tripped BC keypair still operates under JSL.
        byte[] msg = new byte[64];
        sr.nextBytes(msg);
        byte[] sig = sign("SHA256withDSA", JSL, viaJslPriv, msg);
        Assertions.assertTrue(verify("SHA256withDSA", JSL, viaJslPub, msg, sig),
                "a round-tripped BC keypair no longer operates under JSL");
    }

    // -----------------------------------------------------------------
    // AlgorithmParameters — byte-equality of the Dss-Parms codec
    // -----------------------------------------------------------------

    /**
     * The {@code Dss-Parms SEQUENCE { p, q, g }} codec must agree with BC in
     * both directions: same encoding out for the same components, and the same
     * components back from the peer's encoding.
     */
    @Test
    public void algorithmParametersAgreeWithBouncyCastle() throws Exception
    {
        DSAParameterSpec domain = domainOf(jslPair);

        AlgorithmParameters jslAp = AlgorithmParameters.getInstance("DSA", JSL);
        jslAp.init(domain);
        AlgorithmParameters bcAp = AlgorithmParameters.getInstance("DSA", BC);
        bcAp.init(domain);
        Assertions.assertTrue(Arrays.areEqual(bcAp.getEncoded(), jslAp.getEncoded()),
                "JSL and BC encode the same Dss-Parms differently");

        // Each must read the other's encoding back to the same components.
        assertSameDomain(domain, reread(BC, jslAp.getEncoded()), "BC reading a JSL encoding");
        assertSameDomain(domain, reread(JSL, bcAp.getEncoded()), "JSL reading a BC encoding");
    }

    // -----------------------------------------------------------------
    // AlgorithmParameterGenerator — cross-acceptance, not byte-equality
    // -----------------------------------------------------------------

    /**
     * Generated domain parameters are randomised, so there is nothing to
     * compare byte-for-byte. Agreement is that BC ACCEPTS what JSL generates:
     * it must read the parameters back unchanged, build a keypair on them, and
     * that keypair must cross-verify with JSL.
     * <p>
     * The reverse direction — JSL accepting BC's parameters — is covered too,
     * so a codec that only round-trips its own output cannot pass.
     */
    @Test
    public void generatedParametersAreAcceptedByBouncyCastle() throws Exception
    {
        SecureRandom sr = seededRandom("generatedParametersAreAcceptedByBouncyCastle");

        AlgorithmParameterGenerator jslApg = AlgorithmParameterGenerator.getInstance("DSA", JSL);
        jslApg.init(KEY_BITS);
        AlgorithmParameters jslParams = jslApg.generateParameters();
        DSAParameterSpec jslSpec = jslParams.getParameterSpec(DSAParameterSpec.class);
        Assertions.assertEquals(KEY_BITS, jslSpec.getP().bitLength(), "JSL generated p of the wrong size");

        assertSameDomain(jslSpec, reread(BC, jslParams.getEncoded()),
                "BC reading JSL-generated parameters");
        assertCrossOperable(jslSpec, sr, "JSL-generated parameters");

        AlgorithmParameterGenerator bcApg = AlgorithmParameterGenerator.getInstance("DSA", BC);
        bcApg.init(KEY_BITS);
        AlgorithmParameters bcParams = bcApg.generateParameters();
        DSAParameterSpec bcSpec = bcParams.getParameterSpec(DSAParameterSpec.class);

        assertSameDomain(bcSpec, reread(JSL, bcParams.getEncoded()),
                "JSL reading BC-generated parameters");
        assertCrossOperable(bcSpec, sr, "BC-generated parameters");
    }

    // -----------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------

    private static DSAParameterSpec domainOf(KeyPair pair)
    {
        java.security.interfaces.DSAPublicKey pub = (java.security.interfaces.DSAPublicKey) pair.getPublic();
        return new DSAParameterSpec(pub.getParams().getP(), pub.getParams().getQ(), pub.getParams().getG());
    }

    private static DSAParameterSpec reread(String provider, byte[] encoded) throws Exception
    {
        AlgorithmParameters ap = AlgorithmParameters.getInstance("DSA", provider);
        ap.init(encoded);
        return ap.getParameterSpec(DSAParameterSpec.class);
    }

    private static void assertSameDomain(DSAParameterSpec expected, DSAParameterSpec actual, String what)
    {
        Assertions.assertEquals(expected.getP(), actual.getP(), what + ": p differs");
        Assertions.assertEquals(expected.getQ(), actual.getQ(), what + ": q differs");
        Assertions.assertEquals(expected.getG(), actual.getG(), what + ": g differs");
    }

    /**
     * Both providers must build a keypair on the given domain parameters, and
     * each must verify the other's signature under it — the check that makes
     * "accepted" mean usable rather than merely parsed.
     */
    private static void assertCrossOperable(DSAParameterSpec spec, SecureRandom sr, String what)
            throws Exception
    {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("DSA", JSL);
        kpg.initialize(spec);
        KeyPair pair = kpg.generateKeyPair();

        KeyFactory bcKf = KeyFactory.getInstance("DSA", BC);
        PublicKey peerPub = bcKf.generatePublic(new X509EncodedKeySpec(pair.getPublic().getEncoded()));
        PrivateKey peerPriv = bcKf.generatePrivate(new PKCS8EncodedKeySpec(pair.getPrivate().getEncoded()));

        byte[] msg = new byte[64];
        sr.nextBytes(msg);

        Assertions.assertTrue(
                verify("SHA256withDSA", BC, peerPub, msg, sign("SHA256withDSA", JSL, pair.getPrivate(), msg)),
                what + ": BC rejected a JSL signature made under them");
        Assertions.assertTrue(
                verify("SHA256withDSA", JSL, pair.getPublic(), msg, sign("SHA256withDSA", BC, peerPriv, msg)),
                what + ": JSL rejected a BC signature made under them");
    }
}
