/*
 *
 *   Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
 *
 *   Licensed under the Apache License 2.0 (the "License"). You may not use
 *   this file except in compliance with the License.  You can obtain a copy
 *   in the file LICENSE in the source distribution or at
 *   https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE
 *
 */

package jostle.examples.fips;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openssl.jostle.jcajce.spec.UserKeyingMaterialSpec;

import javax.crypto.KeyAgreement;
import javax.crypto.spec.DHParameterSpec;
import java.nio.charset.StandardCharsets;
import java.security.AlgorithmParameterGenerator;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.ECGenParameterSpec;

/**
 * Key agreement in the FIPS module: ECDH and finite-field DH, plain and with a KDF. The 3.5.8 module serves no
 * X25519 or X448. Each party initialises its own `KeyAgreement` with its private key, passes the peer's public
 * key to `doPhase`, and reads the shared secret with `generateSecret`.
 */
public class FipsKeyAgreementExamplesTest
        extends FipsExamples
{
    /**
     * ECDH on P-256, and DH on a named group, each giving a 256-bit AES key.
     */
    @Test
    public void ecdhAndDh()
            throws Exception
    {
        String[] agreements = {"ECDH", "DH"};
        KeyPairGenerator ec = KeyPairGenerator.getInstance("EC", "JSLFIPS");
        ec.initialize(new ECGenParameterSpec("secp256r1"));
        KeyPairGenerator dh = KeyPairGenerator.getInstance("DH", "JSLFIPS");
        dh.initialize(2048);
        for (String name : agreements)
        {
            KeyPairGenerator kpg = name.equals("ECDH") ? ec : dh;
            KeyPair alice = kpg.generateKeyPair();
            KeyPair bob = kpg.generateKeyPair();
            KeyAgreement a = KeyAgreement.getInstance(name, "JSLFIPS");
            a.init(alice.getPrivate());
            a.doPhase(bob.getPublic(), true);
            KeyAgreement b = KeyAgreement.getInstance(name, "JSLFIPS");
            b.init(bob.getPrivate());
            b.doPhase(alice.getPublic(), true);
            Assertions.assertArrayEquals(a.generateSecret("AES").getEncoded(),
                    b.generateSecret("AES").getEncoded(), name);
        }
    }

    /**
     * The module requires the DH subgroup order q. A key on PKCS#3 parameters (p and g only, here freshly
     * generated by JSL) is refused at `init` with `InvalidKeyException`; keys on a named group carry q, including
     * ones rebuilt from a named group's p and g.
     */
    @Test
    public void dhNeedsTheSubgroupOrder()
            throws Exception
    {
        AlgorithmParameterGenerator apg = AlgorithmParameterGenerator.getInstance("DH", "JSL");
        apg.init(1024);
        KeyPairGenerator pkcs3 = KeyPairGenerator.getInstance("DH", "JSL");
        pkcs3.initialize(apg.generateParameters().getParameterSpec(DHParameterSpec.class));
        PrivateKey noQ = KeyFactory.getInstance("DH", "JSLFIPS").generatePrivate(
                new PKCS8EncodedKeySpec(pkcs3.generateKeyPair().getPrivate().getEncoded()));
        KeyAgreement ka = KeyAgreement.getInstance("DH", "JSLFIPS");
        InvalidKeyException e = Assertions.assertThrows(InvalidKeyException.class, () -> ka.init(noQ));
        Assertions.assertTrue(e.getMessage().contains("subgroup order q"), e.getMessage());
    }

    /**
     * The agreements with a built-in KDF: the X9.63 KDF over ECDH and the RFC 2631 KDF over DH, deriving an
     * AES-256 key-encryption key named by the wrap's object identifier, with optional user keying material.
     */
    @Test
    public void agreementsWithAKdf()
            throws Exception
    {
        String[] agreements = {"ECDHwithSHA1KDF", "ECDHwithSHA224KDF", "ECDHwithSHA256KDF", "ECDHwithSHA384KDF",
                "ECDHwithSHA512KDF", "DHwithRFC2631KDF"};
        UserKeyingMaterialSpec ukm = new UserKeyingMaterialSpec("key id 7".getBytes(StandardCharsets.US_ASCII));
        for (String name : agreements)
        {
            KeyPairGenerator kpg = KeyPairGenerator.getInstance(name.startsWith("DH") ? "DH" : "EC", "JSLFIPS");
            kpg.initialize(name.startsWith("DH") ? 2048 : 256);
            KeyPair alice = kpg.generateKeyPair();
            KeyPair bob = kpg.generateKeyPair();
            KeyAgreement a = KeyAgreement.getInstance(name, "JSLFIPS");
            a.init(alice.getPrivate(), ukm);
            a.doPhase(bob.getPublic(), true);
            KeyAgreement b = KeyAgreement.getInstance(name, "JSLFIPS");
            b.init(bob.getPrivate(), ukm);
            b.doPhase(alice.getPublic(), true);
            Assertions.assertArrayEquals(a.generateSecret("2.16.840.1.101.3.4.1.45").getEncoded(),
                    b.generateSecret("2.16.840.1.101.3.4.1.45").getEncoded(), name);
        }
    }

    /**
     * The OpenPGP ECDH agreements (RFC 6637) over NIST curves, with the OpenPGP parameter block as user keying
     * material.
     */
    @Test
    public void openPgpEcdh()
            throws Exception
    {
        String[] agreements = {"ECCDHwithSHA256CKDF", "ECCDHwithSHA384CKDF", "ECCDHwithSHA512CKDF"};
        UserKeyingMaterialSpec param = new UserKeyingMaterialSpec("openpgp param block".getBytes(
                StandardCharsets.US_ASCII));
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC", "JSLFIPS");
        kpg.initialize(new ECGenParameterSpec("secp256r1"));
        for (String name : agreements)
        {
            KeyPair alice = kpg.generateKeyPair();
            KeyPair bob = kpg.generateKeyPair();
            KeyAgreement a = KeyAgreement.getInstance(name, "JSLFIPS");
            a.init(alice.getPrivate(), param);
            a.doPhase(bob.getPublic(), true);
            KeyAgreement b = KeyAgreement.getInstance(name, "JSLFIPS");
            b.init(bob.getPrivate(), param);
            b.doPhase(alice.getPublic(), true);
            Assertions.assertArrayEquals(a.generateSecret("2.16.840.1.101.3.4.1.45").getEncoded(),
                    b.generateSecret("2.16.840.1.101.3.4.1.45").getEncoded(), name);
        }
    }
}
