#!/usr/bin/env python3
"""Regenerate SERVICES.md from `DumpInfo --services`.

Runs the Jostle DumpInfo diagnostic with the --services flag (or reads its
captured output via --input), parses the "Services (N total, grouped by type)"
section, and writes a markdown inventory of every algorithm the provider
registers, grouped by JCA service type, to SERVICES.md at the repo root
(beside README.md).

Usage:
    python3 .claude/skills/update-services-md/scripts/update_services_md.py
    python3 .claude/skills/update-services-md/scripts/update_services_md.py --input dump.txt

The service list is fixed by the provider's registration code, not by the
DumpInfo flag, so the output is identical regardless of how DumpInfo is invoked.
"""
import argparse
import glob
import os
import re
import subprocess
import sys

TYPE_HEADER = re.compile(r"^ {2}(\S+) \((\d+)\):\s*$")
ALGORITHM = re.compile(r"^ {4}(.+?)\s*$")
SECTION_START = re.compile(r"^Services \((\d+) total")
FIPS_SECTION_START = re.compile(r"^FIPS Services \((\d+) total")


def find_repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    candidate = here
    while True:
        if (os.path.isdir(os.path.join(candidate, "jostle"))
                and os.path.isfile(os.path.join(candidate, "README.md"))):
            return candidate
        parent = os.path.dirname(candidate)
        if parent == candidate:
            break
        candidate = parent
    cwd = os.getcwd()
    if (os.path.isdir(os.path.join(cwd, "jostle"))
            and os.path.isfile(os.path.join(cwd, "README.md"))):
        return cwd
    sys.exit("error: could not locate the repo root (a directory with jostle/ and README.md)")


def find_jar(root):
    jars = [j for j in glob.glob(os.path.join(root, "jostle", "build", "libs", "openssl-jostle-*.jar"))
            if not j.endswith("-sources.jar") and not j.endswith("-javadoc.jar")]
    return sorted(jars)[0] if jars else None


def run_dumpinfo(jar, fips_config=None):
    java = "java"
    if os.environ.get("JAVA_HOME"):
        java = os.path.join(os.environ["JAVA_HOME"], "bin", "java")
    cmd = [java, "--enable-native-access=ALL-UNNAMED", "-cp", jar,
           "org.openssl.jostle.util.DumpInfo", "--services"]
    if fips_config:
        cmd += ["--fips-config", fips_config]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        sys.exit("error: 'java' not found; set JAVA_HOME or put java on PATH")
    return proc.stdout


def parse_section(lines, start_re, stop_res):
    start = next((i for i, line in enumerate(lines) if start_re.match(line)), None)
    if start is None:
        return None, []

    total = int(start_re.match(lines[start]).group(1))
    groups = []
    current = None
    for line in lines[start + 1:]:
        if line.startswith(".END") or line.startswith("---") \
                or any(r.match(line) for r in stop_res):
            break
        header = TYPE_HEADER.match(line)
        if header:
            current = (header.group(1), [])
            groups.append(current)
            continue
        algorithm = ALGORITHM.match(line)
        if algorithm and current is not None:
            current[1].append(algorithm.group(1))
    return total, groups


def parse_services(text):
    lines = text.splitlines()
    total, groups = parse_section(lines, SECTION_START, [FIPS_SECTION_START])
    fips_total, fips_groups = parse_section(lines, FIPS_SECTION_START, [])
    return total, groups, fips_total, fips_groups


def render_markdown(total, groups, fips_total=None, fips_groups=None):
    out = [
        "# Jostle Provider — Registered Services",
        "",
        "> Generated by the `update-services-md` skill from `DumpInfo --services`.",
        "> Do not edit by hand — re-run the skill to refresh it.",
        "",
        "The Jostle (`JSL`) provider registers **{0}** services across **{1}** JCA "
        "service types. Each list is the set of algorithm names (and OID aliases) "
        "registered for that type.".format(total, len(groups)),
        "",
    ]
    for service_type, algorithms in groups:
        out.append("## {0} ({1})".format(service_type, len(algorithms)))
        out.append("")
        for index, algorithm in enumerate(algorithms, 1):
            out.append("{0}. `{1}`".format(index, algorithm))
        out.append("")
    if fips_groups:
        out.append("# Jostle FIPS Provider (JSLFIPS) — Registered Services")
        out.append("")
        out.append("The Jostle FIPS (`JSLFIPS`) provider registers **{0}** services across "
                   "**{1}** JCA service types — what the OpenSSL FIPS module serves, not a "
                   "subset filtered against its security policy. The module decides what is "
                   "available: its implementations carry a `fips=yes`/`fips=no` property and "
                   "the lib ctx's `fips=yes` default query excludes the latter, so Triple-DES, "
                   "ChaCha20 and OCB (for instance) are simply not fetchable.".format(
                       fips_total, len(fips_groups)))
        out.append("")
        out.append("**Approval is not asserted here.** Whether a particular operation is "
                   "FIPS-*approved* is a compliance determination against the module's "
                   "security policy (CMVP cert #4985 for OpenSSL FIPS 3.1.2), and it belongs "
                   "to the operator. This provider does not make it, for three reasons: the "
                   "module does not enforce its own validated envelope; OpenSSL 3.1.2 exposes "
                   "no runtime approved-mode indicator; and the policy's non-approved entries "
                   "are usage-scoped — HMAC key length, HKDF key length, X9.63 KDF PRF choice, "
                   "RSA primitive modulus size — which no registration surface can express. "
                   "Deployments needing an enforced restriction should use the JVM's own "
                   "`jdk.security.providers.filter`.")
        out.append("")
        for service_type, algorithms in fips_groups:
            out.append("## {0} ({1})".format(service_type, len(algorithms)))
            out.append("")
            for index, algorithm in enumerate(algorithms, 1):
                out.append("{0}. `{1}`".format(index, algorithm))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description="Regenerate SERVICES.md from DumpInfo --services.")
    parser.add_argument("--input", help="read DumpInfo output from this file instead of running java")
    parser.add_argument("--fips-config",
                        help="JSLFIPS configuration string (e.g. \"fips_module='/path/to/fips.so'\") - "
                             "adds a JSLFIPS section to SERVICES.md")
    args = parser.parse_args()

    root = find_repo_root()
    if args.input:
        with open(args.input, encoding="utf-8") as handle:
            text = handle.read()
    else:
        jar = find_jar(root)
        if not jar:
            sys.exit("error: no jar under jostle/build/libs/ -- build it first: ./gradlew :jostle:jar")
        text = run_dumpinfo(jar, args.fips_config)

    total, groups, fips_total, fips_groups = parse_services(text)
    if not groups:
        sys.exit("error: DumpInfo output had no 'Services (...)' section. The jar may predate the "
                 "--services flag -- rebuild it (./gradlew :jostle:jar) and retry.")

    destination = os.path.join(root, "SERVICES.md")
    with open(destination, "w", encoding="utf-8") as handle:
        handle.write(render_markdown(total, groups, fips_total, fips_groups))
    message = "wrote {0}: {1} services across {2} types".format(destination, total, len(groups))
    if fips_groups:
        message += "; JSLFIPS: {0} services across {1} types".format(fips_total, len(fips_groups))
    print(message)


if __name__ == "__main__":
    main()
