#!/usr/bin/env python3
"""Regenerate SERVICES.md from `DumpInfo --services`.

Runs the Jostle DumpInfo diagnostic with the --services flag (or reads its
captured output via --input), parses the "Services (N total, grouped by type)"
section, and writes a markdown inventory of every algorithm the provider
registers, grouped by JCA service type, to SERVICES.md at the repo root
(beside README.md).

Usage:
    python3 .claude/skills/update-services-md/scripts/update_services_md.py
    python3 .claude/skills/update-services-md/scripts/update_services_md.py --input dump.txt

The service list is fixed by the provider's registration code, not by the
DumpInfo flag, so the output is identical regardless of how DumpInfo is invoked.
"""
import argparse
import glob
import os
import re
import subprocess
import sys

TYPE_HEADER = re.compile(r"^ {2}(\S+) \((\d+)\):\s*$")
ALGORITHM = re.compile(r"^ {4}(.+?)\s*$")
SECTION_START = re.compile(r"^Services \((\d+) total")


def find_repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    candidate = here
    while True:
        if (os.path.isdir(os.path.join(candidate, "jostle"))
                and os.path.isfile(os.path.join(candidate, "README.md"))):
            return candidate
        parent = os.path.dirname(candidate)
        if parent == candidate:
            break
        candidate = parent
    cwd = os.getcwd()
    if (os.path.isdir(os.path.join(cwd, "jostle"))
            and os.path.isfile(os.path.join(cwd, "README.md"))):
        return cwd
    sys.exit("error: could not locate the repo root (a directory with jostle/ and README.md)")


def find_jar(root):
    jars = [j for j in glob.glob(os.path.join(root, "jostle", "build", "libs", "openssl-jostle-*.jar"))
            if not j.endswith("-sources.jar") and not j.endswith("-javadoc.jar")]
    return sorted(jars)[0] if jars else None


def run_dumpinfo(jar):
    java = "java"
    if os.environ.get("JAVA_HOME"):
        java = os.path.join(os.environ["JAVA_HOME"], "bin", "java")
    cmd = [java, "--enable-native-access=ALL-UNNAMED", "-cp", jar,
           "org.openssl.jostle.util.DumpInfo", "--services"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        sys.exit("error: 'java' not found; set JAVA_HOME or put java on PATH")
    return proc.stdout


def parse_services(text):
    lines = text.splitlines()
    start = next((i for i, line in enumerate(lines) if SECTION_START.match(line)), None)
    if start is None:
        return None, []

    total = int(SECTION_START.match(lines[start]).group(1))
    groups = []
    current = None
    for line in lines[start + 1:]:
        if line.startswith(".END") or line.startswith("---"):
            break
        header = TYPE_HEADER.match(line)
        if header:
            current = (header.group(1), [])
            groups.append(current)
            continue
        algorithm = ALGORITHM.match(line)
        if algorithm and current is not None:
            current[1].append(algorithm.group(1))
    return total, groups


def render_markdown(total, groups):
    out = [
        "# Jostle Provider — Registered Services",
        "",
        "> Generated by the `update-services-md` skill from `DumpInfo --services`.",
        "> Do not edit by hand — re-run the skill to refresh it.",
        "",
        "The Jostle (`JSL`) provider registers **{0}** services across **{1}** JCA "
        "service types. Each list is the set of algorithm names (and OID aliases) "
        "registered for that type.".format(total, len(groups)),
        "",
    ]
    for service_type, algorithms in groups:
        out.append("## {0} ({1})".format(service_type, len(algorithms)))
        out.append("")
        for index, algorithm in enumerate(algorithms, 1):
            out.append("{0}. `{1}`".format(index, algorithm))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description="Regenerate SERVICES.md from DumpInfo --services.")
    parser.add_argument("--input", help="read DumpInfo output from this file instead of running java")
    args = parser.parse_args()

    root = find_repo_root()
    if args.input:
        with open(args.input, encoding="utf-8") as handle:
            text = handle.read()
    else:
        jar = find_jar(root)
        if not jar:
            sys.exit("error: no jar under jostle/build/libs/ -- build it first: ./gradlew :jostle:jar")
        text = run_dumpinfo(jar)

    total, groups = parse_services(text)
    if not groups:
        sys.exit("error: DumpInfo output had no 'Services (...)' section. The jar may predate the "
                 "--services flag -- rebuild it (./gradlew :jostle:jar) and retry.")

    destination = os.path.join(root, "SERVICES.md")
    with open(destination, "w", encoding="utf-8") as handle:
        handle.write(render_markdown(total, groups))
    print("wrote {0}: {1} services across {2} types".format(destination, total, len(groups)))


if __name__ == "__main__":
    main()
