//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoBlockCipher_dispose       JoFIPS_JoBlockCipher_dispose
#define JoBlockCipher_doFinal       JoFIPS_JoBlockCipher_doFinal
#define JoBlockCipher_getBlockSize  JoFIPS_JoBlockCipher_getBlockSize
#define JoBlockCipher_getFinalSize  JoFIPS_JoBlockCipher_getFinalSize
#define JoBlockCipher_getUpdateSize JoFIPS_JoBlockCipher_getUpdateSize
#define JoBlockCipher_init          JoFIPS_JoBlockCipher_init
#define JoBlockCipher_make_instance JoFIPS_JoBlockCipher_make_instance
#define JoBlockCipher_update        JoFIPS_JoBlockCipher_update
#define JoBlockCipher_updateAAD     JoFIPS_JoBlockCipher_updateAAD
/* *INDENT-ON* */

#include "block_cipher_ni_ffi.c"
