//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoDH_allocateKex               JoFIPS_JoDH_allocateKex
#define JoDH_disposeKex                JoFIPS_JoDH_disposeKex
#define JoDH_generateKeyPair           JoFIPS_JoDH_generateKeyPair
#define JoDH_generateKeyPairByGroup    JoFIPS_JoDH_generateKeyPairByGroup
#define JoDH_generateParameters        JoFIPS_JoDH_generateParameters
#define JoDH_getComponent              JoFIPS_JoDH_getComponent
#define JoDH_groupSupported            JoFIPS_JoDH_groupSupported
#define JoDH_kexDerive                 JoFIPS_JoDH_kexDerive
#define JoDH_kexInit                   JoFIPS_JoDH_kexInit
#define JoDH_kexSetPeer                JoFIPS_JoDH_kexSetPeer
#define JoDH_makeParamsFromComponents  JoFIPS_JoDH_makeParamsFromComponents
#define JoDH_makePrivateFromComponents JoFIPS_JoDH_makePrivateFromComponents
#define JoDH_makePublicFromComponents  JoFIPS_JoDH_makePublicFromComponents
/* *INDENT-ON* */

#include "dh_ni_ffi.c"
