//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoDSA_allocateSigner            JoFIPS_JoDSA_allocateSigner
#define JoDSA_disposeSigner             JoFIPS_JoDSA_disposeSigner
#define JoDSA_generateKeyPair           JoFIPS_JoDSA_generateKeyPair
#define JoDSA_generateParameters        JoFIPS_JoDSA_generateParameters
#define JoDSA_getComponent              JoFIPS_JoDSA_getComponent
#define JoDSA_initSign                  JoFIPS_JoDSA_initSign
#define JoDSA_initVerify                JoFIPS_JoDSA_initVerify
#define JoDSA_makeParamsFromComponents  JoFIPS_JoDSA_makeParamsFromComponents
#define JoDSA_makePrivateFromComponents JoFIPS_JoDSA_makePrivateFromComponents
#define JoDSA_makePublicFromComponents  JoFIPS_JoDSA_makePublicFromComponents
#define JoDSA_sign                      JoFIPS_JoDSA_sign
#define JoDSA_update                    JoFIPS_JoDSA_update
#define JoDSA_verify                    JoFIPS_JoDSA_verify
/* *INDENT-ON* */

#include "dsa_ni_ffi.c"
