//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoEC_allocateKex               JoFIPS_JoEC_allocateKex
#define JoEC_allocateSigner            JoFIPS_JoEC_allocateSigner
#define JoEC_curveSupported            JoFIPS_JoEC_curveSupported
#define JoEC_disposeKex                JoFIPS_JoEC_disposeKex
#define JoEC_disposeSigner             JoFIPS_JoEC_disposeSigner
#define JoEC_generateKeyPair           JoFIPS_JoEC_generateKeyPair
#define JoEC_getComponent              JoFIPS_JoEC_getComponent
#define JoEC_initSign                  JoFIPS_JoEC_initSign
#define JoEC_initVerify                JoFIPS_JoEC_initVerify
#define JoEC_kexDerive                 JoFIPS_JoEC_kexDerive
#define JoEC_kexInit                   JoFIPS_JoEC_kexInit
#define JoEC_kexSetPeer                JoFIPS_JoEC_kexSetPeer
#define JoEC_makePrivateFromComponents JoFIPS_JoEC_makePrivateFromComponents
#define JoEC_sign                      JoFIPS_JoEC_sign
#define JoEC_update                    JoFIPS_JoEC_update
#define JoEC_verify                    JoFIPS_JoEC_verify
/* *INDENT-ON* */

#include "ec_ni_ffi.c"
