//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoEDDSA_allocateSigner   JoFIPS_JoEDDSA_allocateSigner
#define JoEDDSA_decodePrivateKey JoFIPS_JoEDDSA_decodePrivateKey
#define JoEDDSA_decodePublicKey  JoFIPS_JoEDDSA_decodePublicKey
#define JoEDDSA_disposeSigner    JoFIPS_JoEDDSA_disposeSigner
#define JoEDDSA_generateKeyPair  JoFIPS_JoEDDSA_generateKeyPair
#define JoEDDSA_getPrivateKey    JoFIPS_JoEDDSA_getPrivateKey
#define JoEDDSA_getPublicKey     JoFIPS_JoEDDSA_getPublicKey
#define JoEDDSA_initSign         JoFIPS_JoEDDSA_initSign
#define JoEDDSA_initVerifier     JoFIPS_JoEDDSA_initVerifier
#define JoEDDSA_sign             JoFIPS_JoEDDSA_sign
#define JoEDDSA_update           JoFIPS_JoEDDSA_update
#define JoEDDSA_verify           JoFIPS_JoEDDSA_verify
/* *INDENT-ON* */

#include "ed_ni_ffi.c"
