//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoMLDSA_allocateSigner      JoFIPS_JoMLDSA_allocateSigner
#define JoMLDSA_decodePrivateKey    JoFIPS_JoMLDSA_decodePrivateKey
#define JoMLDSA_decodePublicKey     JoFIPS_JoMLDSA_decodePublicKey
#define JoMLDSA_disposeSigner       JoFIPS_JoMLDSA_disposeSigner
#define JoMLDSA_generateKeyPair     JoFIPS_JoMLDSA_generateKeyPair
#define JoMLDSA_generateKeyPairSeed JoFIPS_JoMLDSA_generateKeyPairSeed
#define JoMLDSA_getPrivateKey       JoFIPS_JoMLDSA_getPrivateKey
#define JoMLDSA_getPublicKey        JoFIPS_JoMLDSA_getPublicKey
#define JoMLDSA_getSeed             JoFIPS_JoMLDSA_getSeed
#define JoMLDSA_initSign            JoFIPS_JoMLDSA_initSign
#define JoMLDSA_initVerifier        JoFIPS_JoMLDSA_initVerifier
#define JoMLDSA_sign                JoFIPS_JoMLDSA_sign
#define JoMLDSA_update              JoFIPS_JoMLDSA_update
#define JoMLDSA_verify              JoFIPS_JoMLDSA_verify
/* *INDENT-ON* */

#include "mldsa_ni_ffi.c"
