//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoRSA_allocateSigner             JoFIPS_JoRSA_allocateSigner
#define JoRSA_decodePrivateComponents    JoFIPS_JoRSA_decodePrivateComponents
#define JoRSA_decodePrivateComponentsCrt JoFIPS_JoRSA_decodePrivateComponentsCrt
#define JoRSA_decodePublicComponents     JoFIPS_JoRSA_decodePublicComponents
#define JoRSA_disposeSigner              JoFIPS_JoRSA_disposeSigner
#define JoRSA_generateKeyPair            JoFIPS_JoRSA_generateKeyPair
#define JoRSA_getComponent               JoFIPS_JoRSA_getComponent
#define JoRSA_initSign                   JoFIPS_JoRSA_initSign
#define JoRSA_initVerify                 JoFIPS_JoRSA_initVerify
#define JoRSA_sign                       JoFIPS_JoRSA_sign
#define JoRSA_update                     JoFIPS_JoRSA_update
#define JoRSA_verify                     JoFIPS_JoRSA_verify
/* *INDENT-ON* */

#include "rsa_ni_ffi.c"
