//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoSLHDSA_allocateSigner      JoFIPS_JoSLHDSA_allocateSigner
#define JoSLHDSA_decodePrivateKey    JoFIPS_JoSLHDSA_decodePrivateKey
#define JoSLHDSA_decodePublicKey     JoFIPS_JoSLHDSA_decodePublicKey
#define JoSLHDSA_disposeSigner       JoFIPS_JoSLHDSA_disposeSigner
#define JoSLHDSA_generateKeyPair     JoFIPS_JoSLHDSA_generateKeyPair
#define JoSLHDSA_generateKeyPairSeed JoFIPS_JoSLHDSA_generateKeyPairSeed
#define JoSLHDSA_getPrivateKey       JoFIPS_JoSLHDSA_getPrivateKey
#define JoSLHDSA_getPublicKey        JoFIPS_JoSLHDSA_getPublicKey
#define JoSLHDSA_initSign            JoFIPS_JoSLHDSA_initSign
#define JoSLHDSA_initVerifier        JoFIPS_JoSLHDSA_initVerifier
#define JoSLHDSA_sign                JoFIPS_JoSLHDSA_sign
#define JoSLHDSA_update              JoFIPS_JoSLHDSA_update
#define JoSLHDSA_verify              JoFIPS_JoSLHDSA_verify
/* *INDENT-ON* */

#include "slh_dsa_ni_ffi.c"
