/*
 *
 *   Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
 *
 *   Licensed under the Apache License 2.0 (the "License"). You may not use
 *   this file except in compliance with the License.  You can obtain a copy
 *   in the file LICENSE in the source distribution or at
 *   https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE
 *
 */

package org.openssl.jostle.test.rand;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The CAVP DRBG vectors carried under {@code src/test/resources/drbg}, loaded
 * from the classpath.
 *
 * <p>Reading this class touches no native code, so a guard over the table runs
 * on the unit legs where the operations-test hook is absent.
 *
 * <p>The file is hashed after normalising line endings to LF, because a checkout
 * may rewrite them.
 *
 * <p>The resource is generated by {@code tools/generate-drbg-vectors.py} and
 * carries one block per {@code (set, file, mechanism, psLen, aiLen)} key. The
 * selection is pinned as a SET of those keys rather than as a count: a subset
 * is an instrument that can silently carry the wrong input, so a key that moves
 * or vanishes must fail by name. See the resource README.
 */
public final class CavpDrbgVectors
{
    private CavpDrbgVectors()
    {
    }

    /** 13 mapped headers x 4 (ps, ai) configurations x 3 sets. */
    public static final int EXPECTED_BLOCKS = 156;

    /** The archive's full header count, as (file, header) pairs: 8 CTR + 7 Hash + 7 HMAC. */
    public static final int ARCHIVE_HEADERS = 22;

    public static final String RESOURCE = "/drbg/cavp-drbg-vectors.txt";

    public static final String MANIFEST = "/drbg/MANIFEST.sha256";

    private static final int COLUMNS = 19;

    /**
     * Section headers that map to a registered SecureRandom name. Every
     * registered CTR name carries {@code useDerivationFunction = true}, so the
     * no-df sections map to nothing; 3KeyTDEA and the truncated SHA-512
     * variants are not registered at all.
     */
    public static final Map<String, List<String>> MAPPED_HEADERS;

    /** Every header the archive carries, mapped or not. */
    public static final Map<String, List<String>> ARCHIVE_HEADERS_BY_FILE;

    static
    {
        Map<String, List<String>> mapped = new LinkedHashMap<String, List<String>>();
        mapped.put("CTR_DRBG", unmodifiable("AES-128 use df", "AES-192 use df", "AES-256 use df"));
        mapped.put("Hash_DRBG", unmodifiable("SHA-1", "SHA-224", "SHA-256", "SHA-384", "SHA-512"));
        mapped.put("HMAC_DRBG", unmodifiable("SHA-1", "SHA-224", "SHA-256", "SHA-384", "SHA-512"));
        MAPPED_HEADERS = Collections.unmodifiableMap(mapped);

        Map<String, List<String>> all = new LinkedHashMap<String, List<String>>();
        all.put("CTR_DRBG", unmodifiable("3KeyTDEA use df", "3KeyTDEA no df",
                "AES-128 use df", "AES-128 no df", "AES-192 use df", "AES-192 no df",
                "AES-256 use df", "AES-256 no df"));
        all.put("Hash_DRBG", unmodifiable("SHA-1", "SHA-224", "SHA-256", "SHA-384", "SHA-512",
                "SHA-512/224", "SHA-512/256"));
        all.put("HMAC_DRBG", unmodifiable("SHA-1", "SHA-224", "SHA-256", "SHA-384", "SHA-512",
                "SHA-512/224", "SHA-512/256"));
        ARCHIVE_HEADERS_BY_FILE = Collections.unmodifiableMap(all);
    }

    private static List<String> unmodifiable(String... values)
    {
        List<String> list = new ArrayList<String>();
        Collections.addAll(list, values);
        return Collections.unmodifiableList(list);
    }

    /** One CAVP COUNT block. Byte arrays are EMPTY, never null, for an absent field. */
    public static final class Vector
    {
        public final String set;
        public final String file;
        public final String mechanism;
        public final int psLen;
        public final int aiLen;
        public final int entropyInputLen;
        public final int nonceLen;
        public final int returnedBitsLen;
        public final int count;
        public final byte[] entropyInput;
        public final byte[] nonce;
        public final byte[] personalizationString;
        public final byte[] entropyInputReseed;
        public final byte[] additionalInputReseed;
        public final byte[] additionalInput1;
        public final byte[] additionalInput2;
        public final byte[] entropyInputPR1;
        public final byte[] entropyInputPR2;
        public final byte[] returnedBits;

        private Vector(String[] f)
        {
            set = f[0];
            file = f[1];
            mechanism = f[2];
            psLen = Integer.parseInt(f[3]);
            aiLen = Integer.parseInt(f[4]);
            entropyInputLen = Integer.parseInt(f[5]);
            nonceLen = Integer.parseInt(f[6]);
            returnedBitsLen = Integer.parseInt(f[7]);
            count = Integer.parseInt(f[8]);
            entropyInput = hex(f[9]);
            nonce = hex(f[10]);
            personalizationString = hex(f[11]);
            entropyInputReseed = hex(f[12]);
            additionalInputReseed = hex(f[13]);
            additionalInput1 = hex(f[14]);
            additionalInput2 = hex(f[15]);
            entropyInputPR1 = hex(f[16]);
            entropyInputPR2 = hex(f[17]);
            returnedBits = hex(f[18]);
        }

        /** The selection key, as the generator wrote it. */
        public String key()
        {
            return set + "|" + file + "|" + mechanism + "|" + psLen + "|" + aiLen;
        }

        /** The OpenSSL EVP_RAND mechanism name. */
        public String openSslMechanism()
        {
            if (file.equals("CTR_DRBG"))
            {
                return "CTR-DRBG";
            }
            return file.equals("Hash_DRBG") ? "HASH-DRBG" : "HMAC-DRBG";
        }

        /** The OpenSSL variant: a cipher SN for CTR, a digest SN otherwise. */
        public String openSslVariant()
        {
            if (file.equals("CTR_DRBG"))
            {
                return mechanism.substring(0, mechanism.indexOf(' ')) + "-CTR";
            }
            return mechanism.equals("SHA-1") ? "SHA1" : "SHA2-" + mechanism.substring(4);
        }

        /** Only the use-df CTR sections are carried, and no Hash/HMAC section uses one. */
        public boolean usesDerivationFunction()
        {
            return file.equals("CTR_DRBG");
        }

        /**
         * The requested instantiation strength, which is the section's own
         * EntropyInputLen for every carried configuration.
         */
        public int strength()
        {
            return entropyInputLen;
        }

        public boolean predictionResistant()
        {
            return set.equals("drbgvectors_pr_true");
        }

        public boolean hasReseed()
        {
            return set.equals("drbgvectors_pr_false");
        }

        @Override
        public String toString()
        {
            return key();
        }
    }

    private static List<Vector> cached;

    /** Loads and caches the table. Fails loudly rather than returning a short list. */
    public static synchronized List<Vector> load()
    {
        if (cached != null)
        {
            return cached;
        }

        cached = Collections.unmodifiableList(parse(resourceBytes()));
        return cached;
    }

    /**
     * Verifies and parses one copy of the resource. The bytes are normalised to
     * LF FIRST, because a checkout may rewrite line endings and the manifest
     * records the generator's LF form.
     */
    public static List<Vector> parse(byte[] raw)
    {
        byte[] normalised = normalise(raw);
        verifyAgainstManifest(normalised);

        List<Vector> vectors = new ArrayList<Vector>();
        BufferedReader reader = new BufferedReader(new InputStreamReader(
                new ByteArrayInputStream(normalised), StandardCharsets.US_ASCII));
        try
        {
            String line;
            int lineNo = 0;
            while ((line = reader.readLine()) != null)
            {
                lineNo++;
                if (line.isEmpty() || line.charAt(0) == '#')
                {
                    continue;
                }
                String[] fields = line.split("\\|", -1);
                if (fields.length != COLUMNS)
                {
                    throw new IllegalStateException(RESOURCE + ":" + lineNo + " has "
                            + fields.length + " columns, expected " + COLUMNS);
                }
                vectors.add(new Vector(fields));
            }
        }
        catch (IOException e)
        {
            throw new UncheckedIOException(e);
        }

        // Vacuity: a parser that reads nothing reports a tidy empty table, and an
        // empty table passes every "for each vector" loop written over it.
        if (vectors.size() != EXPECTED_BLOCKS)
        {
            throw new IllegalStateException("expected " + EXPECTED_BLOCKS + " blocks in "
                    + RESOURCE + ", read " + vectors.size());
        }

        return Collections.unmodifiableList(vectors);
    }

    /** CRLF to LF, so a Windows checkout hashes and parses as the generator wrote it. */
    public static byte[] normalise(byte[] raw)
    {
        String text = new String(raw, StandardCharsets.US_ASCII).replace("\r\n", "\n");
        return text.getBytes(StandardCharsets.US_ASCII);
    }

    /** The resource exactly as the checkout left it, line endings and all. */
    public static byte[] resourceBytes()
    {
        return readResource(RESOURCE);
    }

    /** The sha256 the manifest records for the vector file. */
    public static String manifestSha256()
    {
        String manifest = new String(readResource(MANIFEST), StandardCharsets.US_ASCII);
        for (String line : manifest.split("\n"))
        {
            String trimmed = line.trim();
            if (trimmed.endsWith("cavp-drbg-vectors.txt") && !trimmed.startsWith("#"))
            {
                return trimmed.split("\\s+")[0];
            }
        }
        throw new IllegalStateException(MANIFEST + " records no sha256 for the vector file");
    }

    /** Lower-case hex sha256, so a test can compare what the manifest compares. */
    public static String sha256Hex(byte[] data)
    {
        StringBuilder out = new StringBuilder();
        try
        {
            for (byte b : MessageDigest.getInstance("SHA-256").digest(data))
            {
                out.append(String.format("%02x", b));
            }
        }
        catch (NoSuchAlgorithmException e)
        {
            throw new IllegalStateException("SHA-256 is unavailable", e);
        }
        return out.toString();
    }

    /**
     * The manifest records what the generator wrote, so an edited or truncated
     * resource is a named mismatch rather than a silent change of what is under
     * test.
     */
    private static void verifyAgainstManifest(byte[] normalised)
    {
        String expected = manifestSha256();
        String actual = sha256Hex(normalised);
        if (!expected.equals(actual))
        {
            throw new IllegalStateException(RESOURCE + " does not match " + MANIFEST
                    + ": recorded " + expected + ", found " + actual
                    + " (compared after normalising line endings to LF)");
        }
    }

    private static byte[] readResource(String name)
    {
        InputStream in = CavpDrbgVectors.class.getResourceAsStream(name);
        if (in == null)
        {
            throw new IllegalStateException(name + " is not on the test classpath");
        }
        try
        {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[8192];
            int read;
            while ((read = in.read(buffer)) >= 0)
            {
                out.write(buffer, 0, read);
            }
            in.close();
            return out.toByteArray();
        }
        catch (IOException e)
        {
            throw new UncheckedIOException(e);
        }
    }

    /** The selection keys actually present, in file order. */
    public static Set<String> keys()
    {
        Set<String> keys = new LinkedHashSet<String>();
        for (Vector v : load())
        {
            if (!keys.add(v.key()))
            {
                throw new IllegalStateException("duplicate selection key " + v.key());
            }
        }
        return keys;
    }

    /**
     * The (psLen, aiLen) configurations present per {@code set|file|header}.
     * The lengths are read from the table, never predicted; the shape is
     * asserted.
     */
    public static Map<String, Set<String>> configsByHeader()
    {
        Map<String, Set<String>> out = new LinkedHashMap<String, Set<String>>();
        for (Vector v : load())
        {
            String header = v.set + "|" + v.file + "|" + v.mechanism;
            Set<String> configs = out.get(header);
            if (configs == null)
            {
                configs = new LinkedHashSet<String>();
                out.put(header, configs);
            }
            if (!configs.add(v.psLen + "," + v.aiLen))
            {
                throw new IllegalStateException("duplicate configuration " + v.key());
            }
        }
        return out;
    }

    /** The {@code file|header} pairs the table carries. */
    public static Set<String> headersPresent()
    {
        Set<String> out = new LinkedHashSet<String>();
        for (Vector v : load())
        {
            out.add(v.file + "|" + v.mechanism);
        }
        return out;
    }

    /** The {@code file|header} pairs the archive carries, mapped or not. */
    public static Set<String> archiveHeaders()
    {
        Set<String> out = new LinkedHashSet<String>();
        for (Map.Entry<String, List<String>> e : ARCHIVE_HEADERS_BY_FILE.entrySet())
        {
            for (String header : e.getValue())
            {
                out.add(e.getKey() + "|" + header);
            }
        }
        return out;
    }

    /** The {@code file|header} pairs that map to a registered name. */
    public static Set<String> mappedHeaders()
    {
        Set<String> out = new LinkedHashSet<String>();
        for (Map.Entry<String, List<String>> e : MAPPED_HEADERS.entrySet())
        {
            for (String header : e.getValue())
            {
                out.add(e.getKey() + "|" + header);
            }
        }
        return out;
    }

    private static byte[] hex(String s)
    {
        if ((s.length() & 1) != 0)
        {
            // Halving the length would drop the trailing character, so a
            // truncated field would parse into a shorter value and compare.
            throw new IllegalStateException("odd-length hex field: " + s.length() + " characters");
        }
        int n = s.length() / 2;
        byte[] out = new byte[n];
        for (int i = 0; i < n; i++)
        {
            out[i] = (byte) ((digit(s.charAt(2 * i)) << 4) | digit(s.charAt(2 * i + 1)));
        }
        return out;
    }

    private static int digit(char c)
    {
        int d = Character.digit(c, 16);
        if (d < 0)
        {
            throw new IllegalStateException("not a hex digit: " + c);
        }
        return d;
    }
}
