//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFM bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFM
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffm-wrappers; regenerate rather than hand-editing.
//

/* *INDENT-OFF* */
#define JoX509_allocate         JoFIPS_JoX509_allocate
#define JoX509_allocateCrl      JoFIPS_JoX509_allocateCrl
#define JoX509_crlEntries       JoFIPS_JoX509_crlEntries
#define JoX509_crlEntriesLen    JoFIPS_JoX509_crlEntriesLen
#define JoX509_crlExtensions    JoFIPS_JoX509_crlExtensions
#define JoX509_crlExtensionsLen JoFIPS_JoX509_crlExtensionsLen
#define JoX509_crlFields        JoFIPS_JoX509_crlFields
#define JoX509_crlFieldsLen     JoFIPS_JoX509_crlFieldsLen
#define JoX509_dispose          JoFIPS_JoX509_dispose
#define JoX509_disposeCrl       JoFIPS_JoX509_disposeCrl
#define JoX509_extensions       JoFIPS_JoX509_extensions
#define JoX509_extensionsLen    JoFIPS_JoX509_extensionsLen
#define JoX509_fields           JoFIPS_JoX509_fields
#define JoX509_fieldsLen        JoFIPS_JoX509_fieldsLen
/* *INDENT-ON* */

#include "x509_ni_ffm.c"
