#!/usr/bin/env python3
"""Generate (or check) interface/fips/ffi/<x>_fips_ffi.c rename wrappers.

Each wrapper #defines every Jo-named export of its byte-identical twin to a
JoFIPS_-prefixed name and #includes the twin, so the FIPS interface library
shares no entry-point name with the base one. See
reviews/fips-ffi-distinct-symbols-plan.md and the symbol-collision section of
.claude/guides/native-code.md.

  --check   exit non-zero if any wrapper is missing, stale, orphaned, if the
            CMake glue list is inconsistent, or if a precondition is violated.
            Writes nothing.
"""

import argparse
import pathlib
import re
import sys


def in_cmake(cmake, rel):
    """True if the FIPS tree lists `rel`. Anchored: "fips/ffi/x.c" is a
    substring of "nonfips/ffi/x.c", which made every twin look duplicated."""
    return re.search(r'(?<!non)fips/ffi/' + re.escape(rel) + r'\s*$',
                     cmake, re.M) is not None

FFI = pathlib.Path("interface/fips/ffi")
CMAKE = pathlib.Path("interface/CMakeLists.txt")
PREFIX = "JoFIPS_"

# FIPS-only, already JoFIPS_-named: it is not a twin and has no base counterpart.
SKIP = {"openssl_fips_ffi.c"}

# openssl_ffi.c's wrapper cannot be openssl_fips_ffi.c - that name is taken by
# the FIPS-only capability/init file above.
STEM_OVERRIDE = {"openssl_ffi.c": "openssl_ni"}

HEADER = """//  Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
//
//  Licensed under the Apache License 2.0 (the "License"). You may not use
//  this file except in compliance with the License.  You can obtain a copy
//  in the file LICENSE in the source distribution or at
//  https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE

//
// FIPS interface library glue: the base FFI bridge re-included under
// JoFIPS_-prefixed export names, mirroring the JNI rename pattern
// (see md_fips_jni.c).
//
// The two interface libraries used to export identical names, so a FIPS FFI
// class handed the wrong SymbolLookup resolved into the BASE library and ran
// non-FIPS crypto with no symptom - no functional test can tell two providers
// apart when they compute the same answers. With the names disjoint, and the
// Java side taking the lookup and the prefix as separate parameters, either
// mistake alone now fails at construction (NoSuchElementException) instead.
//
// This file must only ever contain renames. Generated by
// .claude/skills/regen-fips-ffi-wrappers; regenerate rather than hand-editing.
//
"""

# A file-scope definition of a Jo-named function. The '(' may sit on the line
# after the name, which is why this spans newlines - three BlockCipher entry
# points are written that way and a same-line-only pattern silently misses them.
DEF = re.compile(r'^[A-Za-z_][A-Za-z0-9_ \*]*[ \*](Jo[A-Za-z0-9_]*)\s*\(', re.M | re.S)


def twins():
    """The glue files that need a wrapper, in a stable order."""
    return [p for p in sorted(FFI.glob("*.c"))
            if "_fips_" not in p.name and p.name not in SKIP]


def wrapper_path(twin):
    stem = STEM_OVERRIDE.get(twin.name, re.sub(r"_ffi$", "", twin.stem))
    return FFI / f"{stem}_fips_ffi.c"


def render(twin, names):
    width = max(len(n) for n in names)
    body = "\n".join(f"#define {n:<{width}} {PREFIX}{n}" for n in names)
    return (HEADER + "\n/* *INDENT-OFF* */\n" + body
            + "\n/* *INDENT-ON* */\n\n#include \"" + twin.name + "\"\n")


def check_no_cross_file_calls(plan, problems):
    """Per-file renaming is only correct while no glue function calls another
    glue function across files: the caller's translation unit would not carry
    the #define and would fail to link against the FIPS library."""
    owner = {n: t.name for t, ns in plan for n in ns}
    for twin, _ in plan:
        text = twin.read_text()
        # Strip comments so a mention in prose is not read as a call.
        text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
        text = re.sub(r'//[^\n]*', ' ', text)
        for name, home in owner.items():
            if home != twin.name and re.search(r'\b' + re.escape(name) + r'\b', text):
                problems.append(
                    f"{twin.name} references {name}, defined in {home}: per-file "
                    f"renaming would leave that call unresolved in the FIPS library")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify without writing; non-zero exit if stale")
    args = ap.parse_args()

    if not FFI.is_dir():
        print(f"run from the repo root: {FFI} not found", file=sys.stderr)
        return 3

    plan, problems, skipped = [], [], []
    for twin in twins():
        names = sorted(set(DEF.findall(twin.read_text())))
        if names:
            plan.append((twin, names))
        else:
            skipped.append(twin.name)

    check_no_cross_file_calls(plan, problems)

    expected = {wrapper_path(t).name for t, _ in plan}
    for stray in sorted(FFI.glob("*_fips_ffi.c")):
        if stray.name not in expected and stray.name not in SKIP:
            problems.append(f"{stray.name} has no twin - orphaned wrapper, delete it")

    cmake = CMAKE.read_text() if CMAKE.exists() else ""
    total, wrote = 0, 0
    for twin, names in plan:
        out = wrapper_path(twin)
        text = render(twin, names)
        total += len(names)
        if args.check:
            if not out.exists():
                problems.append(f"{out.name} is missing ({len(names)} renames)")
            elif out.read_text() != text:
                problems.append(f"{out.name} is stale - regenerate")
        elif not out.exists() or out.read_text() != text:
            out.write_text(text)
            wrote += 1
        if not in_cmake(cmake, out.name):
            problems.append(f"{out.name} is not in FIPS_FFI_GLUE_SOURCES")
        if in_cmake(cmake, twin.name):
            problems.append(f"fips/ffi/{twin.name} is listed in CMake as well as its "
                            f"wrapper - the twin is compiled through {out.name}, so "
                            f"listing both duplicates every symbol")

    verb = "checked" if args.check else "written"
    print(f"{len(plan)} wrappers {verb}, {total} renames"
          + (f", {wrote} updated" if not args.check else ""))
    if skipped:
        print(f"no Jo exports, not wrapped: {', '.join(skipped)}")

    if problems:
        print("\nPROBLEMS:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1
    print("consistent")
    return 0


if __name__ == "__main__":
    sys.exit(main())
