/*
 *
 *   Copyright 2026 OpenSSL Jostle Authors. All Rights Reserved.
 *
 *   Licensed under the Apache License 2.0 (the "License"). You may not use
 *   this file except in compliance with the License.  You can obtain a copy
 *   in the file LICENSE in the source distribution or at
 *   https://github.com/openssl-projects/openssl-jostle/blob/main/LICENSE
 *
 */

package org.openssl.jostle.test.rsa;

import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openssl.jostle.jcajce.provider.JostleProvider;

import java.math.BigInteger;
import java.security.InvalidParameterException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.Provider;
import java.security.Security;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.RSAPublicKeySpec;
import java.security.spec.X509EncodedKeySpec;

/**
 * MT-46 / MT-51: the RSA GENERATION floor and the RSA IMPORT floor, asserted
 * together.
 *
 * <h2>Why one test holds both</h2>
 *
 * <p>They were three orders of magnitude apart and nobody noticed, because each
 * half was individually defensible. Generation refused 512 (our documented
 * 1024-bit policy); import accepted a TWELVE-bit modulus, so the generation
 * policy could be bypassed by encoding a key and reading it back. The defect
 * was the gap, not either number.
 *
 * <p>So the two floors are pinned in one place with both values stated. A
 * future change that moves one without the other has to walk past the other's
 * assertion to do it.
 *
 * <h2>The import floor is deliberately LOWER, and that is not an oversight</h2>
 *
 * <p>Generating a weak key is a choice the provider should refuse. Reading one
 * that already exists is something a caller legitimately does - a stored
 * 768-bit key still needs decoding to be inspected, migrated, or rejected by an
 * application's own policy. 512 is the JDK's import floor; our 1024 generation
 * floor is stricter than both references, which is a deliberate security
 * decision and stays.
 */
public class RSAKeyFloorTest
{
    private static Provider jsl;
    private static Provider bc;

    /** Mirrors RSAKeyPairGenerator.MIN_KEY_SIZE_BITS. */
    private static final int GENERATION_FLOOR = 1024;
    /** Mirrors RSAKeyFactorySpi.MIN_IMPORT_MODULUS_BITS. */
    private static final int IMPORT_FLOOR = 512;

    @BeforeAll
    public static void setUp()
    {
        jsl = Security.getProvider(JostleProvider.PROVIDER_NAME);
        if (jsl == null)
        {
            jsl = new JostleProvider();
            Security.addProvider(jsl);
        }
        bc = Security.getProvider("BC");
        if (bc == null)
        {
            bc = new BouncyCastleProvider();
            Security.addProvider(bc);
        }
    }

    @Test
    public void generationFloorRefusesBelowOneThousandAndTwentyFour() throws Exception
    {
        KeyPairGenerator g = KeyPairGenerator.getInstance("RSA", jsl);
        Assertions.assertThrows(InvalidParameterException.class,
                () -> g.initialize(GENERATION_FLOOR - 512),
                "generation must refuse 512");
        // And the boundary holds from the other side: the floor itself works.
        KeyPairGenerator ok = KeyPairGenerator.getInstance("RSA", jsl);
        ok.initialize(GENERATION_FLOOR);
        Assertions.assertNotNull(ok.generateKeyPair().getPublic());
    }

    /**
     * The MT-46 defect itself: a 12-bit modulus, through the spec the RSA
     * factory genuinely supports.
     */
    @Test
    public void importFloorRefusesAToyModulus() throws Exception
    {
        KeyFactory kf = KeyFactory.getInstance("RSA", jsl);
        InvalidKeySpecException e = Assertions.assertThrows(InvalidKeySpecException.class,
                () -> kf.generatePublic(new RSAPublicKeySpec(
                        BigInteger.valueOf(3233), BigInteger.valueOf(17))));
        Assertions.assertTrue(e.getMessage().contains("512"),
                "the refusal should name the floor: " + e.getMessage());
    }

    /**
     * The floors are DIFFERENT, deliberately - and a real key at the import
     * floor still imports.
     *
     * <p>This is the assertion that makes the pair meaningful. A future edit
     * that "tidies" the import floor up to 1024 breaks it, and has to justify
     * doing so rather than doing it silently.
     */
    @Test
    public void importFloorIsBelowTheGenerationFloorAndAKeyAtItStillImports() throws Exception
    {
        Assertions.assertTrue(IMPORT_FLOOR < GENERATION_FLOOR,
                "the import floor is deliberately below the generation floor");

        // A genuine 512-bit key, generated by BouncyCastle because ours refuses
        // to make one - which is the whole point of the asymmetry.
        KeyPairGenerator g = KeyPairGenerator.getInstance("RSA", bc);
        g.initialize(IMPORT_FLOOR);
        KeyPair kp = g.generateKeyPair();

        KeyFactory kf = KeyFactory.getInstance("RSA", jsl);
        java.security.interfaces.RSAPublicKey imported =
                (java.security.interfaces.RSAPublicKey) kf.generatePublic(
                        new X509EncodedKeySpec(kp.getPublic().getEncoded()));
        Assertions.assertEquals(IMPORT_FLOOR, imported.getModulus().bitLength(),
                "a key AT the import floor must import");
    }

    /**
     * The encoded path is floored too, not just the component path.
     *
     * <p>MT-46 was found through {@code RSAPublicKeySpec}; flooring only that
     * branch would leave {@code X509EncodedKeySpec} as an open door to the same
     * defect, which is the shape of half-fix this project keeps finding.
     */
    @Test
    public void theEncodedImportPathIsFlooredToo() throws Exception
    {
        KeyPairGenerator g = KeyPairGenerator.getInstance("RSA", bc);
        g.initialize(256);
        KeyPair weak = g.generateKeyPair();
        KeyFactory kf = KeyFactory.getInstance("RSA", jsl);
        Assertions.assertThrows(InvalidKeySpecException.class,
                () -> kf.generatePublic(new X509EncodedKeySpec(weak.getPublic().getEncoded())),
                "a 256-bit key must not import through the encoded path either");
        Assertions.assertThrows(InvalidKeySpecException.class,
                () -> kf.generatePrivate(new java.security.spec.PKCS8EncodedKeySpec(
                        weak.getPrivate().getEncoded())),
                "nor the private half");
    }
}
